"""empty message

Revision ID: 7d28290be954
Revises: cf6db65eaa8f
Create Date: 2018-09-12 15:27:52.159374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d28290be954'
down_revision = 'cf6db65eaa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin', 'date')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin', 'date', 'period')
    )
    op.create_table('technical_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('indicator', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin', 'date', 'period', 'indicator')
    )
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('weightedAverage', sa.Float(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin', 'date', 'period')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker')
    op.drop_table('technical_indicator')
    op.drop_table('model')
    op.drop_table('book')
    # ### end Alembic commands ###
