"""empty message

Revision ID: cf6db65eaa8f
Revises: 
Create Date: 2018-09-11 21:29:23.866714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6db65eaa8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_trends')
    # ### end Alembic commands ###
